services:
  laravel:
    build: 
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: crislainesc/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: crislainesc/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge